name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Run linting
        run: yarn lint || echo "Linting issues detected"
      
      - name: Check TypeScript compilation
        run: npx tsc --noEmit 